In [39]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

# Load 
upload 12 months of cycling data from 07-2020 to 06-2021

In [40]:
#upload 12 months of cycling data 
df_1 = pd.read_csv('Cyclistic 12 months data/202007-divvy-tripdata.csv')
df_2 = pd.read_csv('Cyclistic 12 months data/202008-divvy-tripdata.csv')
df_3 = pd.read_csv('Cyclistic 12 months data/202009-divvy-tripdata.csv')
df_4 = pd.read_csv('Cyclistic 12 months data/202010-divvy-tripdata.csv')
df_5 = pd.read_csv('Cyclistic 12 months data/202011-divvy-tripdata.csv')
df_6 = pd.read_csv('Cyclistic 12 months data/202012-divvy-tripdata.csv')
df_7 = pd.read_csv('Cyclistic 12 months data/202101-divvy-tripdata.csv')
df_8 = pd.read_csv('Cyclistic 12 months data/202102-divvy-tripdata.csv')
df_9 = pd.read_csv('Cyclistic 12 months data/202103-divvy-tripdata.csv')
df_10 = pd.read_csv('Cyclistic 12 months data/202104-divvy-tripdata.csv')
df_11 = pd.read_csv('Cyclistic 12 months data/202105-divvy-tripdata.csv')
df_12 = pd.read_csv('Cyclistic 12 months data/202106-divvy-tripdata.csv')

KeyboardInterrupt:

# Cleaning Phase 

- dropping duplicates in all dataframes 
- convert 'started_at' and 'ended_at' to appropriate datetime format
- calculate ride length and delete ride length which are less than 00:00:00 because it's impossible to have
a negative ride length 
- Change day of week to numeric variables. Monday = 0 and Sunday = 6

In [ ]:
#merging all 12 dataframes into one and removing duplicates 
df = [df_1,df_2,df_3,df_4,df_5,df_6,df_7,df_8,df_9,df_10,df_11,df_12]
df_final = pd.concat(df).drop_duplicates()
df_final.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,762198876D69004D,docked_bike,2020-07-09 15:22:02,2020-07-09 15:25:52,Ritchie Ct & Banks St,180.0,Wells St & Evergreen Ave,291.0,41.906866,-87.626217,41.906724,-87.634830,member
1,BEC9C9FBA0D4CF1B,docked_bike,2020-07-24 23:56:30,2020-07-25 00:20:17,Halsted St & Roscoe St,299.0,Broadway & Ridge Ave,461.0,41.943670,-87.648950,41.984045,-87.660274,member
2,D2FD8EA432C77EC1,docked_bike,2020-07-08 19:49:07,2020-07-08 19:56:22,Lake Shore Dr & Diversey Pkwy,329.0,Clark St & Wellington Ave,156.0,41.932588,-87.636427,41.936497,-87.647539,casual
3,54AE594E20B35881,docked_bike,2020-07-17 19:06:42,2020-07-17 19:27:38,LaSalle St & Illinois St,181.0,Clark St & Armitage Ave,94.0,41.890762,-87.631697,41.918306,-87.636282,casual
4,54025FDC7440B56F,docked_bike,2020-07-04 10:39:57,2020-07-04 10:45:05,Lake Shore Dr & North Blvd,268.0,Clark St & Schiller St,301.0,41.911722,-87.626804,41.907993,-87.631501,member

In [ ]:
df_final['month'] = pd.DatetimeIndex(df_final['started_at']).month
df_final['year'] = pd.DatetimeIndex(df_final['started_at']).year

In [ ]:
#obtain the list of dataframe column ['started_at']
#Obtain the list of dataframe column ['ended_at']
#convert to datetime format 
#when a csv file is imported and a dataframe is made, datatime objects in the file
#are read as strings and difficult to perform operations such as time difference 

df_final['started_at']=pd.to_datetime(pd.Series(df_final['started_at']))
df_final['ended_at']=pd.to_datetime(pd.Series(df_final['ended_at']))

#subtract started_at from ended_at 
#find the ride_length on each dataframe 
df_final['ride_length']=df_final['ended_at']-df_final['started_at']

#Monday = 0 
#Sunday = 6 
df_final['day_of_week']=df_final['started_at'].dt.dayofweek 


#removing ride_lengths that have negative values 
df_final = df_final[df_final['ride_length'] >= '0 days']

df_final.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,month,year,ride_length,day_of_week
0,762198876D69004D,docked_bike,2020-07-09 15:22:02,2020-07-09 15:25:52,Ritchie Ct & Banks St,180.0,Wells St & Evergreen Ave,291.0,41.906866,-87.626217,41.906724,-87.634830,member,7,2020,0 days 00:03:50,3
1,BEC9C9FBA0D4CF1B,docked_bike,2020-07-24 23:56:30,2020-07-25 00:20:17,Halsted St & Roscoe St,299.0,Broadway & Ridge Ave,461.0,41.943670,-87.648950,41.984045,-87.660274,member,7,2020,0 days 00:23:47,4
2,D2FD8EA432C77EC1,docked_bike,2020-07-08 19:49:07,2020-07-08 19:56:22,Lake Shore Dr & Diversey Pkwy,329.0,Clark St & Wellington Ave,156.0,41.932588,-87.636427,41.936497,-87.647539,casual,7,2020,0 days 00:07:15,2
3,54AE594E20B35881,docked_bike,2020-07-17 19:06:42,2020-07-17 19:27:38,LaSalle St & Illinois St,181.0,Clark St & Armitage Ave,94.0,41.890762,-87.631697,41.918306,-87.636282,casual,7,2020,0 days 00:20:56,4
4,54025FDC7440B56F,docked_bike,2020-07-04 10:39:57,2020-07-04 10:45:05,Lake Shore Dr & North Blvd,268.0,Clark St & Schiller St,301.0,41.911722,-87.626804,41.907993,-87.631501,member,7,2020,0 days 00:05:08,5

# Analyze Phase 

###  Obtain the summary ride lengths from annual membership riders and casual riders 
- Which day(s) and month(s) do casual riders and annual membership riders prefer to cycle? 
- What's the average ride length of casual riders and annual membership riders? 
- What's the peak time of cycling for casual riders and annual membership riders? 
- Total number of ride lengths in each day of casual riders and annual membership riders?
- Favourite spot to ride? 

Once the questions above are answered, results are exported as a csv file to upload in Google Sheet to create data visualizations of the analyse phase.

In [ ]:
#members 
members_df = df_final[df_final['member_casual']=='member']
#casual members 
casual_df = df_final[df_final['member_casual']=='casual']
#print(casual['day_of_week'].value_counts().to_frame().idxmax())
#print(casual['day_of_week'].value_counts().idxmax())
name_of_month=['01-2021','02-2021','03-2021','04-2021','05-2021','06-2021','07-2020','08-2020','09-2020','10-2020','11-2020','12-2020']
#create dataframe 
casual_day = pd.DataFrame(name_of_month,columns=['Month_Year'])
value = [] 
#Monday = 0 
#Sunday = 6 
day_of_week = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

for month in range(1,13): 
    #if month=1, then we are analysing for January 2021
    casual = casual_df[casual_df['month']==month]  
    #if month=1, which day of week in Jan has most Cyclistic casual users 
    result = casual['day_of_week'].value_counts().idxmax() 
    value.append(day_of_week[result])
    #print ('Favourite Day of the week casual users use Cyclistic the most in', name_of_month[month-1],'is' ,day_of_week[result])

#inserting the result into the casual_day dataframe
casual_day['Day']=value 
casual_day['Membership']='Casual'

In [ ]:
#for Cyclistic members 
member_day = pd.DataFrame(name_of_month,columns=['Month_Year'])
value = []
for month in range(1,13): 
    members = members_df[members_df['month']==month]
    result = members['day_of_week'].value_counts().idxmax()
    value.append(day_of_week[result])
    #print ('Favourite Day of the week members use Cyclistic the most in', name_of_month[month-1],'is' ,day_of_week[result])

member_day["Day"]=value
member_day["Membership"]="Member"

In [ ]:
#Mean ride_lengths per months from casual members 


#casual_rider_length = casual_df[casual_df['month']==7]
#casual_rider_length['ride_length'].describe()
value = []
#Average of ride lengths per month 
for month in range(1,13): 
    casual_month = casual_df[casual_df['month']==month]
    casual_rider_mean_length = casual_month['ride_length'].mean()
    value.append(casual_rider_mean_length)
    #print("Average Ride Length of Casual Member on",name_of_month[month-1],":",casual_rider_mean_length)


casual_day["Average Ride Length"]=value

In [ ]:

#Average of ride lengths per month of members
value = []
for month in range(1,13): 
    member_month = members_df[members_df['month']==month]
    member_rider_mean_length = member_month['ride_length'].mean()
    value.append(member_rider_mean_length)
    #print("Average Ride Length of Casual Member on",name_of_month[month-1],":",member_rider_mean_length)

member_day["Average Ride Length"]=value

In [ ]:
#Total ride length per month from casual members
value = []
for month in range(1,13): 
    casual_month = casual_df[casual_df['month']==month]
    casual_rider_total_length = casual_month['ride_length'].sum()
    value.append(casual_rider_total_length)
    #print("Total Ride Length of Casual Member on",name_of_month[month-1],":",member_rider_total_length)
    
casual_day["Total Ride Length"]=value

In [ ]:
#Total ride length per month from  member 
value = []
for month in range(1,13): 
    member_month = members_df[members_df['month']==month]
    member_rider_total_length = member_month['ride_length'].sum()
    value.append(member_rider_total_length)
    #print("Total Ride Length of Casual Member on",name_of_month[month-1],":",member_rider_total_length)
    
member_day["Total Ride Length"]=value

In [ ]:
#Most frequent start station name of members
value = [] 
members_df['start_station_name'].fillna(0)
members_df['start_station_name'].value_counts()

for month in range(1,13): 
    member_month = members_df[members_df['month']==month]
    member_start_station = member_month['start_station_name'].value_counts().idxmax()
    value.append(member_start_station)
    #print("Top start station of members",name_of_month[month-1],":",member_start_station)
    
member_day["Top Start Station"]=value

In [ ]:
#Most frequent end station name of members

members_df['end_station_name'].fillna(0)
members_df['end_station_name'].value_counts()
value = []

for month in range(1,13): 
    member_month = members_df[members_df['month']==month]
    member_end_station = member_month['end_station_name'].value_counts().idxmax()
    value.append(member_end_station)
    #print("Top end station of members",name_of_month[month-1],":",member_end_station)
    
member_day["Top End Station"]=value

In [ ]:
#Most frequent start station name of casual members
casual_df['start_station_name'].fillna(0)
casual_df['start_station_name'].value_counts()
value = []
for month in range(1,13): 
    casual_month = casual_df[casual_df['month']==month]
    casual_start_station = casual_month['start_station_name'].value_counts().idxmax()
    value.append(casual_start_station)
    #print("Top start station on of casual members",name_of_month[month-1],":",casual_start_station)

casual_day["Top Start Station"]=value

In [ ]:
#Most frequent end station name of casual members

casual_df['end_station_name'].fillna(0)
casual_df['end_station_name'].value_counts()
value = []
for month in range(1,13): 
    casual_month = casual_df[casual_df['month']==month]
    casual_end_station = casual_month['end_station_name'].value_counts().idxmax()
    value.append(casual_end_station)
    #print("Top end station of casual members",name_of_month[month-1],":",casual_start_station)

casual_day["Top End Station"]=value

In [ ]:
#casual_df['peak_hour']=casual_df['started_at'].dt.hour
casual_df_copy = casual_df.copy()
casual_df_copy['time_stamp_hour'] = casual_df_copy['started_at'].astype(str).str[10:13]
casual_df = casual_df_copy
#casual_df.head()

In [ ]:
#Finding peak hour for casual member 

value = []
total = []
for month in range(1,13): 
    casual_month = casual_df[casual_df['month']==month]
    casual_peak_hour = casual_month['time_stamp_hour'].value_counts().idxmax()
    total_number = max(casual_month['time_stamp_hour'].value_counts())
    value.append(casual_peak_hour)
    total.append(total_number)
    #print("Casual Member Peak hour on ",name_of_month[month-1],":",casual_peak_hour,":00:00","Number:",total_number)

casual_day["Peak Hour Time"]=value
casual_day["Number at Peak Hour"]=total
#casual_day.head()

In [ ]:
members_df_copy = members_df.copy()
members_df_copy['time_stamp_hour'] = members_df_copy['started_at'].astype(str).str[10:13]
members_df = members_df_copy
#members_df.head()

In [ ]:
#Finding peak hour for member 
value=[]
total=[]
for month in range(1,13): 
    member_month = members_df[members_df['month']==month]
    member_peak_hour = member_month['time_stamp_hour'].value_counts().idxmax()
    total_number = max(member_month['time_stamp_hour'].value_counts())
    value.append(member_peak_hour)
    total.append(total_number)
    #print(" Member Peak hour on ",name_of_month[month-1],":",member_peak_hour,":00:00","Number:",total_number)

member_day["Peak Hour Time"]=value
member_day["Number at Peak Hour"]=total
#member_day.head()

# Cleaning 

* `Peak Hour Time` format changed from e.g. `17` to `17:00`
*  Combine the aggregated results of casual users and members of Cyclistic into one dataset

In [ ]:
member_day.head()

,Month_Year,Day,Membership,Average Ride Length,Total Ride Length,Top Start Station,Top End Station,Peak Hour Time,Number at Peak Hour
0,01-2021,Friday,Member,0 days 00:12:52.338702915,703 days 15:24:01,Clark St & Elm St,Dearborn St & Erie St,17,7359
1,02-2021,Wednesday,Member,0 days 00:18:01.325086728,494 days 05:50:09,Dearborn St & Erie St,Dearborn St & Erie St,17,4088
2,03-2021,Tuesday,Member,0 days 00:13:58.203126081,1401 days 11:41:40,Clark St & Elm St,Clark St & Elm St,17,15720
3,04-2021,Friday,Member,0 days 00:14:41.352659701,2046 days 12:48:16,Clark St & Elm St,Clark St & Elm St,17,22354
4,05-2021,Saturday,Member,0 days 00:14:38.340997033,2792 days 17:57:27,Clark St & Elm St,Clark St & Elm St,17,29079

In [ ]:
casual_day.head()

,Month_Year,Day,Membership,Average Ride Length,Total Ride Length,Top Start Station,Top End Station,Peak Hour Time,Number at Peak Hour
0,01-2021,Saturday,Casual,0 days 00:25:41.075398796,323 days 03:27:43,Lake Shore Dr & Monroe St,Millennium Park,15,1670
1,02-2021,Saturday,Casual,0 days 00:49:22.393741980,347 days 08:40:11,Millennium Park,Millennium Park,16,1076
2,03-2021,Saturday,Casual,0 days 00:38:09.551147182,2226 days 19:12:42,Lake Shore Dr & Monroe St,Lake Shore Dr & Monroe St,17,9252
3,04-2021,Saturday,Casual,0 days 00:38:01.379389609,3606 days 22:18:26,Lake Shore Dr & Monroe St,Lake Shore Dr & Monroe St,17,15093
4,05-2021,Saturday,Casual,0 days 00:38:13.857973033,6820 days 22:26:55,Streeter Dr & Grand Ave,Streeter Dr & Grand Ave,17,24708

In [ ]:
#combining both dataframes together 
frames = [casual_day,member_day]
final = pd.concat(frames,ignore_index=True,sort=False)
final[["Month","Year"]]=final.Month_Year.str.split("-",expand=True)
final = final.drop('Month_Year',axis=1)
first_column = final.pop('Year')
second_column = final.pop('Month')
final.insert(0,'Year',first_column)
final.insert(1,'Month',second_column)
final['Peak Hour Time'] = final['Peak Hour Time'].astype(str) + ":00"
final = final.sort_values(by=['Year','Month'])

In [42]:
#final look of the dataframe 
final.head()
final.to_csv('Summary_Analysis.csv',index=False)

## Further Analysis 

* Casual users and members' cycling time pattern 
* Casual users and members' bike preference

In [43]:
casual_ride_type=casual_df['rideable_type'].value_counts()
casual_ride_type_df = pd.DataFrame({'rideable_type': casual_ride_type.index, 'count': casual_ride_type.values})
casual_ride_type_df

# Export as csv file
casual_ride_type_df.to_csv('Casual_Rideabletype.csv',index=False)

In [44]:
member_ride_type=members_df['rideable_type'].value_counts()
member_ride_type_df = pd.DataFrame({'rideable_type': member_ride_type.index, 'count': member_ride_type.values})
member_ride_type_df


# Export as csv file
member_ride_type_df.to_csv('Member_Rideabletype.csv',index=False)

In [30]:
casual_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,month,year,ride_length,day_of_week,time_stamp_hour
2,D2FD8EA432C77EC1,docked_bike,2020-07-08 19:49:07,2020-07-08 19:56:22,Lake Shore Dr & Diversey Pkwy,329.0,Clark St & Wellington Ave,156.0,41.932588,-87.636427,41.936497,-87.647539,casual,7,2020,0 days 00:07:15,2,19
3,54AE594E20B35881,docked_bike,2020-07-17 19:06:42,2020-07-17 19:27:38,LaSalle St & Illinois St,181.0,Clark St & Armitage Ave,94.0,41.890762,-87.631697,41.918306,-87.636282,casual,7,2020,0 days 00:20:56,4,19
5,65636B619E24257F,docked_bike,2020-07-28 16:33:03,2020-07-28 16:49:10,Fairbanks St & Superior St,635.0,Wells St & Concord Ln,289.0,41.895748,-87.620104,41.912133,-87.634656,casual,7,2020,0 days 00:16:07,1,16
13,7FA38D309B160B59,docked_bike,2020-07-08 23:06:14,2020-07-08 23:12:24,Wells St & Elm St,182.0,State St & Pearson St,106.0,41.903222,-87.634324,41.897448,-87.628722,casual,7,2020,0 days 00:06:10,2,23
16,8CE8D05B0044D078,docked_bike,2020-07-28 17:19:52,2020-07-28 17:43:41,Lake Shore Dr & Belmont Ave,334.0,Lake Shore Dr & Wellington Ave,157.0,41.940775,-87.639192,41.936688,-87.636829,casual,7,2020,0 days 00:23:49,1,17

In [36]:
#Casual users' Cycling Hours 
casual_time_cycle = casual_df["time_stamp_hour"].value_counts()
casual_time_cycle_df = pd.DataFrame({'time_stamp_hour': casual_time_cycle.index, 'count': casual_time_cycle.values})

# Display the resulting DataFrame
casual_time_cycle_df = casual_time_cycle_df.sort_values(by='time_stamp_hour',ascending=True)

# Export as csv file
casual_time_cycle_df.to_csv('Casual_CyclingHours.csv',index=False)

In [37]:
# Cyclistic member cycling hours 
member_time_cycle=members_df["time_stamp_hour"].value_counts()
member_time_cycle_df = pd.DataFrame({'time_stamp_hour': member_time_cycle.index, 'count': member_time_cycle.values})
member_time_cycle_df=member_time_cycle_df.sort_values(by='time_stamp_hour',ascending=True)
# Export as csv file
member_time_cycle_df.to_csv('Member_CyclingHours.csv',index=False)

**We will proceed to connect the dataframes gathered from the results above to Power BI**